### PR TITLE
Two interesting commits

### PR DESCRIPTION
**Pull request by ioef**
- One for building via docker so the host environment not need to have the libraries installed
- One for parsing the WX Reports and presenting it to human readable format

### CODE REVIEW

**Comment by na7q** [comment]
I will take a look at this soon! Thanks!

**Comment by na7q** [comment]
After looking, this overwrites the raw packet data. Which is not good. 
Data should be kept intact. I would consider some other methods with updating it in the station view.
I'll think about this as I update things. 

I just released a BIG update, so I may start digging into some parsing for WX & Mic-E position reports, statuses, and comments as well possibly displaying devices in the station views.

For now I'll close this commit until a better option is considered.

**Comment by ioef** [comment]
It's ok.
From my side i will continue working upon this solution, refining it, since it covers my needs completely. Furthermore i don't believe that at this point of execution such raw data are needed, especially to be presented as is to the UI. As you might have observed the rest of the data remain untouched.

73 de SV2JLD
Merry Xmas

**Comment by na7q** [comment]
Raw data is very important to me, and has helped me find and resolve many issues with other software and radios. It's just good practice to never modify the original data. You never know why someone might need it! It should have priority over UI.

Regardless I think you have a great start and I may use the code when I get to it. I have some other ideas where parsing and displaying the data is needed. We are making great progress either way!

Thanks!

**Comment by cpacejo** [comment]
@ioef THANK YOU for this Dockerfile!  This is the only way I've been able to get this project to compile.

**Comment by na7q** [comment]
> @ioef THANK YOU for this Dockerfile! This is the only way I've been able to get this project to compile.

It's very easy without Docker when you've never really used it haha. I've not used Docker at all. So did you have to adapt anything to make it work with mine? Also I'm putting the latest code under the "stable" branch at the moment.

**Comment by cpacejo** [comment]
Ah thanks, I didn't realize you had switched to `stable`.

I was able to use that Dockerfile unmodified for both your `master` and `stable` branches.  I haven't tried it against ge0rg's master.  It produces APKs successfully though I haven't had a chance to test them yet.

I previously had tried using the instructions in README.md of your fork.  The first issue for me was obtaining Java 8: Debian no longer packages it, but I was able to install from Ubuntu's repositories.

When I did get the build to run, I always encountered the error that `assembleDebug` (or `assembleRelease`) was not a valid task.  And `assemble` by itself "succeeded" but did nothing.  I do not know or understand Gradle at all so I was unable to debug this.

(I also don't know Docker very well but thankfully it just worked.  Though I think it does re-download Gradle each time I run it.  So I will look into fixing that.)

BTW I am excited to see what changes you've made already and to make some myself.  Top of my list are Digirig support (which I think you've added already?), extended symbol support, bulletin display, and options to filter out and/or notate iGated and repeated traffic.

**Comment by na7q** [comment]
Digirig is added. What is the added symbol support you're thinking of?

I have some bulletin code from a while back where I had it working. It's still on my list of things to do. Next to group messaging.

IGate traffic is able to semi filtered on my latest stable builds.

I would love to chat and collaborate. As it would be most beneficial since I'm pretty well alone on the majority of the project at this point. I'm working on some more big updates right now. Including an add-on mobile display app. Or a hud as some call it.

Screenshot_20250217-132418

**Comment by cpacejo** [comment]
Oh I love the idea of a HUD!

Re: symbol tables, specifically the added overlays defined here: https://www.aprs.org/symbols/symbols-new.txt  APRSDroid seems to display them fine when received, but the input dialog only supports very few overlays.

Testing the latest stable now, seems to work great, just one minor issue of duplicate log entries (seems always in groups of 3 or 4).  I can look into that to get my feet wet with the code base.

Just got my Digirig Lite today, which I realized actually uses a different PTT mechanism from Digirig Mobile.  (Lite uses GPIO, vs. Mobile's RTS control.)  It also works via VOX control (right channel) which seems to work OK with the default AFSK settings.  That's something also I'd be interested to add but will take me a while to figure out USB HID control in Android.

**Comment by na7q** [comment]
What's the duplicate log entries you're referring to? 

Glad to have you on board!

**Comment by cpacejo** [comment]
Re: duplicate log entries, I'm not seeing it any longer.  I was seeing every message received show up in the log 3 to 4 times in quick succession.  (Full duplicates, including the path.)  If I see it again I'll take a screenshot and open an issue.

BTW found you on Patreon, I didn't realize you are also behind the SMS Gateway.  I'm a fan!

**Pull request closed without merging**
